env:
    credentials: "ENCRYPTED[!19334c485f77bf5ef0d48e58bd50701cba79a08ebbf518ef7e7cd4436317020616d5492853a03ad370d947ca50e32019!]"
    rcloneconfig: "ENCRYPTED[!1749fb012864383f98672f46c0ed771b18024cabec0409625abfbcb7a7127ecd7b16b3e8d516637614599f0d1cda7f3e!]"
    tokentl: "ENCRYPTED[!aa090cd88b75f559eddb2b8689aa1fba21dd8ee8b5f6e5388de3ba9cd4e8fd5a67e2e9015a819f36b8db5672365545d3!]"
    idtl: "ENCRYPTED[!b6b3b60e83872912ded9c29c2c68df7deb43db4ce875d86acfc71586b0bd53393092525dcbf74972de4995fadb87e5f2!]"
    lunch: lunch blaze_citrus-userdebug
    make: make bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "darknius09"
       - git config --global user.email "darkniuslightnest@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy 298:blaze/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repoo init -q --no-repo-verify --depth=1 -u https://github.com/ProjectBlaze/manifest.git -b 13 -g default,-mips,-darwin,-notdefault
      - git clone --depth 1 https://github.com/Night-Raids-Reborn/local_manifest -b 13-n .repo/local_manifests
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 && repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="Free_Palestine"
      - export BUILD_HOSTNAME="Free_Palestine"
      - export KBUILD_BUILD_USER="FreePalestine"
      - export KBUILD_BUILD_HOST="Nanomachine"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/ysl/ && ls blaze-*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz 298:blaze -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"

